### ISSUE TITLE
stdClass not found

### ISSUE THREAD

**Issue by bertrandchartier** [silecs/moodle-local-resourcenotif#11]
Thanks for the update,
Error with restricted activities
![image](https://user-images.githubusercontent.com/18231601/112112872-5ddceb00-8bb6-11eb-843a-6992a381a9ce.png)

**Comment by GuillaumeAllegre** [comment]
sorry for this bug, fixed in #fb8e3b6

**Comment by soleimaniha** [comment]
The error is back again!
Using Moodle 3.10.3 and the latest plugin
Thanks

**Comment by soleimaniha** [comment]
![Screenshot from 2021-05-10 23-38-20](https://user-images.githubusercontent.com/55549207/117712136-2ddebb00-b1e9-11eb-8005-491343a4df1e.png)
The "backslash" in line 54 is gone again!!
